name = "mowjet"
compatibility_date = "2025-09-03"

type = "javascript"   # указываем тип проекта

[site]
bucket = ".vercel/output/static"   # выходной каталог Pages
entry-point = "."                  # корень проекта
